const LOGIN = '/auth/login';
const LOGINGOOGLE = '/auth/oauth2/google';
const REGISTR = '/auth/register';
const FIRESTSECTION = '/static/homepage/first-section';
const SECONDSECTION = '/static/homepage/second-section';
const NEED = '/static/homepage/pet-needs';
const INFORMATIONS  = '/static/homepage/footer';
const PETS = '/pets?filter=';
const PETDETAILS = '/pets/:id';
